# Fall 2022 Calendar of In-Class Activities {-}


This calendar only lists the in-class activities, RStudio labs and exams each week. For required readings and videos as well as due dates for assignments, refer to the calendar at:  
[https://mtstateintrostats.github.io/Syllabus/#Course_calendar](https://mtstateintrostats.github.io/Syllabus/#Course_calendar)

\begin{longtable}{|l|l|l|l|p{.55\textwidth}|}
\hline
\textbf{Week}& \textbf{Day}& \textbf{Date}& \textbf{Activity} \\ \hline
\endhead

1& W& 8/24& Syllabus Review \\*
1& F& 8/26& Intro to Data \\ \hline
2& M& 8/29& American Indian Address Part A \\*
2& W& 8/31& American Indian Address Part B \\* 
2& F& 9/2& Week 2 Lab \\ \hline
3& M& 9/5& (\textit{No class}) \\*
3& W& 9/7& Myopia and Nightlights \\*
3& F& 9/9& Week 3 Lab \\ \hline
4& M& 9/12& Movie Profits --- Linear Regression \\*
4& W& 9/14& Movie Profits --- Correlation \\*
4& F& 9/16& Week 4 Lab \\ \hline
5& M& 9/19& Exam 1 Review \\*
5& W& 9/21& Group Midterm Exam 1 \\*	
5& F& 9/23& Midterm Exam 1 \\ \hline
6& M& 9/26& Helper Hinderer --- Simulation HT \\*
6& W& 9/28& Helper Hinderer --- Simulation HT continued \\*	
6& F& 9/30& Week 6 Lab \\ \hline
7& M& 10/3& Handedness of Male Boxers --- Theory HT \\*
7& W& 10/5&  Handedness of Male Boxers --- Theory CI\\*
7& F& 10/7& Week 7 Lab \\ \hline
8& M& 10/10& Good Samaritan --- Simulation HT \\*
8& W& 10/12& Good Samaritan --- Simulation CI \\*	
8& F& 10/14& Week 8 Lab \\ \hline
9& M& 10/17& Helmet Use and Head Injuries --- Theory HT \\*
9& W& 10/19& Helmet Use and Head Injuries --- Theory CI \\*	
9& F& 10/21& Week 9 Lab \\ \hline
10& M& 10/24& Exam 2 Review \\*
10& W& 10/26& Group Midterm Exam 2 \\*
10& F& 10/28& Midterm Exam 2\\ \hline
11& M& 10/31& COVID and Air Pollution \\*
11& W& 11/2& Color Interference \\*	
11& F& 11/4& Week 11 Lab \\ \hline
12& M& 11/7& Does Behavior Impact Performance? \\*
12& W& 11/9& Week 12 Lab \\*
12& F& 11/11& (\textit{No class}) \\ \hline
13& M& 11/14& Diving Penguins  \\*
13& W& 11/16& Golf Driving Distances \\*
13& F& 11/18& Week 13 Lab \\ \hline
Holiday& M--F& 11/21--11/25& \textbf{No Class --- Fall Break} \\ \hline
14& M& 11/28& What's the probability? \\*
14& W& 11/30& Relative Risk \\*
14& F& 12/2& Week 14 Lab \\ \hline
15& M& 12/5& Final Exam Review \\*
15& W& 12/7& Final Group Exam Part 1 \\*
15& F& 12/9& Final Group Exam Part 2 \\ \hline
Finals& Thursday & 12/13 6 - 7:50 pm & Common Final Exam \\
&  &  & See \url{www.montana.edu/registrar/Schedules.html} \\ \hline

\end{longtable}

\nocite{*}

