# Study Design

## Module 2 Reading Guide: Sampling, Experimental Design, and Scope of Inference

### Sections 1.4 (Observational studies), 1.5 (Experiments), and 1.6 (Scope of inference) {-}

\setstretch{1}

**Videos**  

* 1.4to1.6

\setstretch{1.25}

#### Reminders from Section 1.2 {-}

**Explanatory variable**: The variable researchers think _may be_ affecting the other variable.  What the researchers control/assign in an experiment.  If comparing groups, the explanatory variable puts the observational units into groups.

**Response variable**: The variable researchers think _may be_ influenced by the other variable.  This variable is always observed, never controlled or assigned.

#### Vocabulary {-}

Observational study:
\rgs

\rgi Observational data:
\rgs

\rgi Prospective study:
\rgs

\rgi Retrospective study:
\rgs

Confounding variable:
\rgs

Experiment:
\rgs

\rgi Randomized experiment:
\rgs

\rgi Blocking:
\rgs

\rgi Treatment group:
\rgs

\rgi Control group:
\rgs

\rgi Placebo:
\rgs

\rgi Placebo effect:
\rgs

\rgi Blinding:
\rgs

Scope of inference:
\rgs

Generalizability:
\rgs

Causation:
\rgs

#### Notes {-}

What are the four principles of a well-designed randomized experiment?  
\rgs
\rgs
\rgs

Fill in the appropriate scope of inference for each study design.
\begin{center}
\begin{tabular}{|p{2in}|p{2in}|p{2in}|}
\hline
 & \multicolumn{2}{|c|}{\textbf{Study Type}} \\ \hline
 \textbf{Selection of Cases} & Randomized experiment & Observational study \\ \hline
 Random sample && \\ 
 (and no other sampling bias) & & \\ 
  & & \\
   & & \\ \hline
   Non-random sample && \\ 
   (or other sampling bias) & & \\ 
  & & \\
   & & \\ \hline
\end{tabular}
\end{center}

\rgs

True or False: Observational studies can show an association between two variables, but cannot determine a causal relationship.
	
True or False: In order for an experiment to be valid, a placebo must be used.

True or False: If random sampling of the target population is used, and no other types of bias are suspected, results from the sample can be generalized to the entire target population.

True or False: If random sampling of the target population is used, and no other types of bias are suspected, results from the sample can be inferred as a causal relationship between the explanatory and response variables.

\newpage
