# Study Design

## Reading Guide: Sampling, Experimental Design, and Scope of Inference

### Section 1.3 (Sampling principles and strategies) {-}

**Videos**  

* 1.3

\setstretch{1.25}

#### Vocabulary {-}

(Target) Population:
\rgs

Sample:
\rgs

Anecdotal evidence:
\rgs

Bias:
\rgs

\rgi Selection bias:
\rgs

\rgi Non-response bias:
\rgs

\rgi Response bias:
\rgs

Convenience sample:
\rgs

Simple Random Sample:
\rgs

Non-response rate:
\rgs

Representative:
\rgs

#### Notes {-}

Ideally, how should we sample cases from our target population?  Using what sampling method? 
\rgs

##### Notes on types of sampling bias {-}

* Someone must first be _chosen_ to be in a study and refuse to participate in order to have **non-response bias**.

* There must be a valid reason for someone to lie or be untruthful to justify saying **response bias** is present.  Yes, anyone could lie at any time to any question.  Response bias is when those lies are predictable and systematic based on outside influences.
\rgs


True or False: Convenience sampling tends to result in non-response bias.

True or False: Volunteer sampling tends to result in response bias.

True or False: Random sampling helps to resolve selection bias, but has no impact on non-response or response bias.


### Sections 1.4 (Observational studies), 1.5 (Experiments), and 1.6 (Scope of inference) {-}

\setstretch{1}

**Videos**  

* 1.4to1.6

\setstretch{1.25}

#### Reminders from Section 1.2 {-}

**Explanatory variable**: The variable researchers think _may be_ affecting the other variable.  What the researchers control/assign in an experiment.  If comparing groups, the explanatory variable puts the observational units into groups.

**Response variable**: The variable researchers think _may be_ influenced by the other variable.  This variable is always observed, never controlled or assigned.

#### Vocabulary {-}

Observational study:
\rgs

\rgi Observational data:
\rgs

\rgi Prospective study:
\rgs

\rgi Retrospective study:
\rgs

Confounding variable:
\rgs

Experiment:
\rgs

\rgi Randomized experiment:
\rgs

\rgi Blocking:
\rgs

\rgi Treatment group:
\rgs

\rgi Control group:
\rgs

\rgi Placebo:
\rgs

\rgi Placebo effect:
\rgs

\rgi Blinding:
\rgs

Scope of inference:
\rgs

Generalizability:
\rgs

Causation:
\rgs

#### Notes {-}

What are the four principles of a well-designed randomized experiment?  
\rgs
\rgs
\rgs

Fill in the appropriate scope of inference for each study design.
\begin{center}
\begin{tabular}{|p{2in}|p{2in}|p{2in}|}
\hline
 & \multicolumn{2}{|c|}{\textbf{Study Type}} \\ \hline
 \textbf{Selection of Cases} & Randomized experiment & Observational study \\ \hline
 Random sample && \\ 
 (and no other sampling bias) & & \\ 
  & & \\
   & & \\ \hline
   Non-random sample && \\ 
   (or other sampling bias) & & \\ 
  & & \\
   & & \\ \hline
\end{tabular}
\end{center}

\rgs

True or False: Observational studies can show an association between two variables, but cannot determine a causal relationship.
	
True or False: In order for an experiment to be valid, a placebo must be used.

True or False: If random sampling of the target population is used, and no other types of bias are suspected, results from the sample can be generalized to the entire target population.

True or False: If random sampling of the target population is used, and no other types of bias are suspected, results from the sample can be inferred as a causal relationship between the explanatory and response variables.


\newpage

## Activity: Study Design - Part A

\setstretch{1}

### Learning outcomes

* Explain the purpose of random sampling and its effect on scope of inference.

* Identify the types of bias present in a study.

### Terminology review

In this today's activity, we will examine different types of sampling bias and how to determine which population or sub-population the results apply to. Some terms covered in this activity are:

* Population

* Sample

* Parameter **Introduce parameter of interest?**
    
* Statistic

* Selection bias

* Response bias

* Non-response bias

To review these concepts, see Sections 1.3 through 1.6 in the textbook.  

\newpage

### Types of sampling bias. **Complete Q1 before class - do we want them to complete questions before class?**.  

In today's activity, we will look at sampling and types of bias (selection, non-response, or response).

In these next questions, identify the target population, the sample selected, the variable, and the type of bias present.

1. To determine if the proportion of out-of-state undergraduate students at Montana State University has increased in the last 10 years, a statistics instructor sent an email survey to 500 randomly selected current undergraduate students.  One of the questions on the survey asked whether they had in-state or out-of-state residency.  She only received 378 responses.
\vspace{0.25in}

    Target population: 
\vspace{0.3in}

    Sample:
\vspace{0.3in}

    Variable:
\vspace{0.3in}

    Type(s) of bias:
\vspace{0.3in}

2.  **Recently, a survey was conducted to assess current presidential approval in the United States.  A random sample of 6395 US adults was taken.  One of the questions asked in the survey was, "Do you agree or disagree with the President on many or nearly all of the top issues facing the country today?" Of those surveyed, 42% said they did agree.**
\vspace{0.25in}

    Target population: 
\vspace{0.3in}

    Sample:
\vspace{0.3in}

    Variable:
\vspace{0.3in}

    Type(s) of bias:
\vspace{0.3in}

\newpage

3. A television station is interested in predicting whether or not a local referendum to legalize marijuana for adult use will pass. It asks its viewers to phone in and indicate whether they are in favor or opposed to the referendum. Of the 2241 viewers who phoned in, forty-five percent were opposed to legalizing marijuana.
\vspace{0.1in}

    Target population: 
\vspace{0.3in}

    Sample:
\vspace{0.3in}

    Variable:
\vspace{0.3in}

    Type(s) of bias:
\vspace{0.3in}

4. To gauge the interest in a new swimming pool, a local organization stood outside of the Bogart Pool in Bozeman, MT, during open hours.  One of the questions they asked was, "Since the Bogart Pool is in such bad repair, don't you agree that the city should fund a new pool?"
\vspace{0.1in}

    Target population: 
\vspace{0.3in}

    Sample:
\vspace{0.3in}

    Variable:
\vspace{0.3in}

    Type(s) of bias:
\vspace{0.3in}

\newpage

5. The Bozeman school district is interested in surveying parents of students about their opinions on returning to in-person classes following the COVID-19 pandemic.  They divided the school district into 10 divisions based on location and randomly surveyed 20 households within each division.  Explain why selection bias would be present in this study design.
\vspace{1in}

6.  What is the purpose of random selection of a sample from the population? 

\vspace{0.8in}



\newpage

### Take-home messages

1.	If the sample is selected using a random and non-biased method of selection (i.e., a random sample of the target population with no response or non-response bias), then the results of the study can be generalized to the target population.  When using biased methods of selection, the results only apply to the sample selected or similar observational units.


