## Week 3 - Activity 4:  What's the probability?

\setstretch{1}

### Learning outcomes

* Recognize and simulate probabilities as long-run frequencies.

* Construct two-way tables to evaluate conditional probabilities.

### Terminology review

In today's activity, we will cover two-way tables and probability.  Some terms covered in this activity are:

* Proportions 

* Probability

* Conditional probability

* Two-way tables

To review these concepts, see Sections 2.1 and 2.2 in the textbook.  


\newpage

### "Current" Population Survey: 1985
The Current Population Survey (CPS) in 1985 is a survey sponsored by the Census Bureau and the Bureau of Labor Statistics to track labor force statistics for the United States population.  The following table describes the variables in the data set:

| **Variable** | **Description** |
|--	|---------------	|
| `educ` | Number of years of education |
| `south` | Whether lives in southern region of the US: `S` = lives in south, `NS` = does not live in south  |
| `sex` | Sex: `M` = male, `F` = female  |
| `exper` | Number of years of work experience (inferred from age and education) |
| `union` | Whether union member: `Union` or `Not` |
| `wage` | Wage (dollars per hour)  |
| `age` | Age (years)  |
| `race` | Race: `W` = white, `NW` = not white	|
| `sector` | Sector of the economy: `clerical`, `const` (construction),  `management`, `manufacturing`, `professional`, `sales`, `service`, `other` |
| `married` | Marital status: `Married` or `Single` |

#### Vocabulary review. Complete Q1--Q4 before class. {-}

1. What are the observational units?

\vspace{0.5in}

2.  Which variables are categorical?

\vspace{1in}

3.  What type(s) of plot could be used to display the proportion of individuals in each sector of the economy? 

\vspace{1in}

4. What type(s) of plot could be used to display the association between whether an individual is a union member and the sector of the economy in which they work?

\vspace{1in}

\newpage

### Probability 

5. Since the early 1980s, the rapid antigen detection test (RADT) of group A *streptococci* has been used to detect strep throat. A recent study of the accuracy of this test shows that the **sensitivity**, the probability of a positive RADT given the person has strep throat, is 86% in children, while the **specificity**, the probability of a negative RADT given the person does not have strep throat, is 92% in children.  The **prevalence**, the probability of having group A strep, is 37% in children. 
\vspace{1mm}

    Let $A$ = the event the child has strep throat, and $B$ = the event the child has a positive RADT.
\vspace{0.1in}

    a. Identify what each numerical value given in the problem represents in probability notation.
\vspace{.1in}

        0.86 =  
\vspace{.1in}
 
        0.92 =  
\vspace{.1in}

        0.37 =  
\vspace{.1in}

    b. Create a hypothetical two-way table to represent the situation.  Recall that in a two-way table, the explanatory variable should be your column headers (similar to the $x$-axis in a segmented bar graph!) while the response variable becomes the row headers.
\begin{center}
    \renewcommand{\arraystretch}{1.5}
    \begin{tabular}{cccc} \hline
    \hspace{1in} & \hspace{1in} & \hspace{1in} & Total \\ \hline
    & & & \\ 
    & & & \\ 
    & & & \\ \hline
    Total & & & 100,000 \\ \hline
    \end{tabular}
    \end{center}
\vspace{.1in}

    c. Find $P(A \mbox{ and } B)$. What does this probability represent in the context of the problem?
\vspace{.8in}

    d. Find the probability that a child with a positive RADT actually has strep throat. What is the notation used for this probability?
\vspace{.8in}

    e.  What is the probability that a child does not have strep given that they have a positive RADT?  What is the notation used for this probability?

\newpage

6. In a computer store, 30% of the computers in stock are laptops and 70% are desktops.  Five percent of the laptops are on sale, while 10% of the desktops are on sale.
\vspace{1mm}

    Let $L$ = the event the computer is a laptop, and $S$ = the event the computer is on sale.
\vspace{0.1in}

    a. Identify what each numerical value given in the problem represents in probability notation.
\vspace{.1in}

        0.30 =  
 \vspace{.1in}
 
        0.70 =  
\vspace{.1in}

        0.05 =  
\vspace{.1in}

        0.10 =  
\vspace{.1in}

    b. Create a hypothetical two-way table to represent the situation.  
\renewcommand{\arraystretch}{1.5}
\begin{center}
\begin{tabular}{cccc} \hline
\hspace{1in} & \hspace{1in} & \hspace{1in} & Total \\ \hline
& & & \\ 
& & & \\ 
& & & \\ \hline
Total & & & 100,000 \\ \hline
\end{tabular}
\end{center}
\vspace{.1in}

    c. Calculate the probability that a randomly selected computer will be a desktop, given that the computer is on sale. What is the notation used for this probability?
\vspace{.8in}


    d. Find $P(S^C | L^C)$. What does this probability represent in context of the problem?
\vspace{1in}

    e. What is the probability a randomly selected computer is both a laptop and on sale?  Give the appropriate probability notation.


\newpage 

### Learning Outcomes

1.  Conditional probabilities are calculated dependent on a second variable.  In probability notation, the variable following `|` is the variable on which we are conditioning.  The denominator used to calculate the probability will be the total for the variable on which we are conditioning.  


2. ?????

\newpage

### Additional notes

Use this space to summarize your thoughts and take additional notes on today's activity and material covered.


