# Exam 1 Review

Use the provided data set from the Islands (ExamReviewData.csv) and the Exam 1 Review `R` script file to answer the following questions.  Each adult (>21) islander was selected at random from all the adult islanders.  

| **Variable** 	| **Description** |
|----	|-------------	|
| `Island` | Name of Island that the Islander resides on |
| `City` | Name of City in which the Islander resides |
| `Population` | Population of the City |
| `Name` | Name of Islander |
| `Consent` | Whether the Islander consented to be in the study |
| `Gender` | Gender of Islander (M = male, F = Female) |
| `Age` | Age of Islander |
| `Married` | Marital status of Islander |
| `Smoking_Status` | Whether the Islander is a current smoker |
| `Children` | Whether the Islander has children |
| `weight_kg` | Weight measured in kg |
| `height_cm` | Height measured in cm |
| `respitory_rate` | Breaths per minute |
| `Type_of_Music` | Music type (Classical or Heavy Medal) Islander was randomly assigned to listen to |
| `Before_PuzzleCube` | Time to complete puzzle cube (minutes) before listening to assigned music |
| `After_PuzzleCube` | Time to complete puzzle cube (minutes) after listening to assigned music |
| `Diff_PuzzleCube` | Difference in time to complete puzzle cube (minutes) for Before - After listening to assigned music |
| `Education_Level` | Highest level of education completed (note: missing data depicted by missing) |
| `Balance_Test` | Time balanced measured in seconds with eyes closed |
| `Blood_Glucose_before` | Level of blood glucose (mg/dL) before consuming assigned drink |
| `Heart_Rate_before` | Heart rate (bpm) before consuming assigned drink |
| `Type_of_Drink` | Type of drink (EnergyDrink or Cola) Islander was randomly assigned to drink |
| `Heart_Rate_after` | Heart rate (bpm) after consuming assigned drink |
| `Blood_Glucose_after` | Level of blood glucose (mg/dL) after consuming assigned drink |
| `Diff_Heart_Rate` | Difference in heart rate (bpm) for Before - After consuming assigned drink |
| `Diff_Blood_Glucose` | Difference in blood glucose (mg/dL) for Before - After consuming assigned drink |


1. What are the observational units?

\vspace{0.3in}

2. List all the variables that are categorical.

\vspace{0.8in}

3. List all the variables that are quantitative.

\vspace{0.8in}

4. What type of bias may be present in this study?  Explain.

\vspace{0.5in}

5. Choose a single categorical variable. Use the Exam 1 Review `R` script file to find the appropriate summary statistic and graphical display of the data.

\rgi Variable: 

\rgi Summary Statistic (with notation):

\rgi \rgi Interpretation:
    
\vspace{0.3in}
    
\rgi Type of Graph:

\vspace{0.3in}
    
\rgi Sketch of the graph:

\vspace{2in}

\rgi To what group could the results of this study be applies to?

\vspace{0.3in}

\newpage

6.  Choose two categorical variables.   Use the Exam 1 Review `R` script file to find the appropriate summary statistic and graphical display of the data.

\rgi Explanatory Variable:

\rgi Response variable:

\rgi Summary Statistic (with notation):

\rgi \rgi Interpretation:
    
\vspace{0.3in}
    
\rgi Type of Graph:

\vspace{0.3in}
    
\rgi Sketch of the graph:

\vspace{2in}

\rgi Based on the graph, does there appear to be an association between the two variables?  Explain your answer.

\vspace{0.5in}

\rgi Is this an observational study or a randomized experiment?  Explain your answer.

\vspace{0.5in}

\rgi What is the scope of inference for this study?

\newpage


7. Choose one categorical variable and one quantitative variable.  Use the Exam 1 Review `R` script file to find the appropriate summary statistic and graphical display of the data.

\rgi Explanatory Variable:

\rgi Response Variable:

\rgi Summary Statistic (with notation):

\rgi \rgi Interpretation:
    
\vspace{0.3in}
    
\rgi Type of Graph:

\vspace{0.3in}
    
\rgi Sketch of the graph:

\vspace{1.5in}

\rgi Based on the graph, does there appear to be an association between the two variables?  Explain your answer.

\vspace{0.5in}

\rgi Compare the two plots using the four characteristics to describe plots of quantitative variables.

\rgi \rgi Shape:

\vspace{0.2in}

\rgi \rgi Center:

\vspace{0.2in}

\rgi \rgi Spread:

\vspace{0.2in}

\rgi \rgi Outliers:

\vspace{0.2in}

\rgi Is this an observational study or a randomized experiment?  Explain your answer.

\vspace{0.5in}

\rgi What is the scope of inference for this study?

\newpage
    
    
8.   Choose two quantitative variables.   Use the Exam 1 Review `R` script file to find the appropriate summary statistic and graphical display of the data.

\rgi Explanatory Variable:

\rgi Response Variable:

\rgi Summary Statistic (with notation):

\rgi Slope:

\vspace{0.2in}

\rgi \rgi Interpretation:
    
\vspace{0.3in}
    
\rgi Correlation:

\vspace{0.2in}

\rgi \rgi Interpretation:
    
\vspace{0.3in}

\rgi Coefficient of Determination:

\vspace{0.2in}

\rgi \rgi Interpretation:
    
\vspace{0.3in}

\rgi Type of Graph:

\vspace{0.3in}
    
\rgi Sketch of the graph:

\vspace{2in}

\rgi Based on the graph, does there appear to be an association between the two variables?  Explain your answer.

\vspace{0.5in}

\rgi Compare the two plots using the four characteristics to describe scatterplots.

\rgi \rgi Form:

\vspace{0.2in}

\rgi \rgi Direction:

\vspace{0.2in}

\rgi \rgi Strength:

\vspace{0.2in}

\rgi \rgi Outliers:

\vspace{0.2in}

\rgi Is this an observational study or a randomized experiment?  Explain your answer.

\vspace{0.5in}

\rgi What is the scope of inference for this study?

\newpage

9. As far back as medieval times, peppers and other spices have been touted for their potential health benefits, as many possess antioxidant and anti-inflammatory properties. Chili peppers increase the body’s ability to break down lipids, which in turn can reduce the risk of hypertension, Type II diabetes, and cardiovascular disease.   Researchers randomly assigned US adult volunteers to either eat one red-hot chili pepper a day for one month or not.  Before and at the end of the study the cholesterol level for each participant was measured.  The researchers hoped to show that eating one red-hot chili pepper a day will reduce cholesterol levels.  They found that of those who consumed at least one red-hot chili pepper a day, 33.6% had lower cholesterol levels at the end of the study.  Of those who did not eat a chili pepper, 21.6% had lower cholesterol levels at the end of the study.  Twenty-five percent of the participants were assigned to eat a red-hot chili pepper each day for one month.
\vspace{1mm}

    Let $A$ = participant ate one red-hot chili pepper each day, and $B$ = participant had lower cholesterol levels at the end of the study
\vspace{0.1in}

    a.	Identify what each numerical value given in the problem represents in probability notation.
\vspace{0.1in}

        0.336 = 
\vspace{0.1in}
    
        0.216 =
\vspace{0.1in}
    
        0.25 = 
\vspace{0.1in}

    b. Create a hypothetical two-way table to represent the situation.  
\vspace{0.1in}
\begin{center}
    \renewcommand{\arraystretch}{1.5}
    \begin{tabular}{cccc} \hline
    \hspace{1in} & \hspace{1in} & \hspace{1in} & Total \\ \hline
    & & & \\ 
    & & & \\ 
    & & & \\ \hline
    Total & & & 100,000 \\ \hline
    \end{tabular}
\end{center}
\vspace{0.1in}

    c.  If a randomly selected participant was assigned to eat peppers, what is the probability they did not have lower cholesterol levels at the end of the study? What is the notation used for this probability?
\vspace{0.5in}

    d. What is the probability that a randomly selected participant was not assigned to eat peppers and did have lower cholesterol levels?  What is the notation used for this probability?
\vspace{0.5in}

    e.  Find the probability $P(A^C | B^C)$. What does this probability represent in context of the problem?
\vspace{0.5in}

\newpage