# Exam 2 Review

Use the provided data set from the Islands (ExamReviewData.csv) and the Exam 2 Review `R` script file to answer the following questions.  Each adult (>21) islander was selected at random from all the adult islanders.  

| **Variable** 	| **Description** |
|----	|-------------	|
| `Island` | Name of Island that the Islander resides on |
| `City` | Name of City in which the Islander resides |
| `Population` | Population of the City |
| `Name` | Name of Islander |
| `Consent` | Whether the Islander consented to be in the study |
| `Gender` | Gender of Islander (M = male, F = Female) |
| `Age` | Age of Islander |
| `Married` | Marital status of Islander |
| `Smoking_Status` | Whether the Islander is a current smoker |
| `Children` | Whether the Islander has children |
| `weight_kg` | Weight measured in kg |
| `height_cm` | Height measured in cm |
| `respitory_rate` | Breaths per minute |
| `Type_of_Music` | Music type (Classical or Heavy Medal) Islander was randomly assigned to listen to |
| `Before_PuzzleCube` | Time to complete puzzle cube (minutes) before listening to assigned music |
| `After_PuzzleCube` | Time to complete puzzle cube (minutes) after listening to assigned music |
| `Diff_PuzzleCube` | Difference in time to complete puzzle cube (minutes) for Before - After listening to assigned music |
| `Education_Level` | Highest level of education completed (note: missing data depicted by missing) |
| `Balance_Test` | Time balanced measured in seconds with eyes closed |
| `Blood_Glucose_before` | Level of blood glucose (mg/dL) before consuming assigned drink |
| `Heart_Rate_before` | Heart rate (bpm) before consuming assigned drink |
| `Type_of_Drink` | Type of drink (EnergyDrink or Cola) Islander was randomly assigned to drink |
| `Heart_Rate_after` | Heart rate (bpm) after consuming assigned drink |
| `Blood_Glucose_after` | Level of blood glucose (mg/dL) after consuming assigned drink |
| `Diff_Heart_Rate` | Difference in heart rate (bpm) for Before - After consuming assigned drink |
| `Diff_Blood_Glucose` | Difference in blood glucose (mg/dL) for Before - After consuming assigned drink |

1.  Write a research question involving a single categorical variable that can be answered using the data set.  

\vspace{0.8in}

2. Use the provided Exam 2 Review `R` script file and analyze this research question.

\rgi Parameter of Interest:
    
\vspace{0.3in}
    
\rgi Null Hypothesis:
        
\rgi \rgi Notation:
    
\vspace{0.3in}
    
\rgi \rgi Words:
        
\vspace{0.5in}
    
\rgi Alternative Hypothesis:
    
\rgi \rgi Notation:
    
\vspace{0.3in}
    
\rgi \rgi Words:
        
\vspace{0.5in}
   
\rgi Statistic:
    
\vspace{0.3in}

\rgi Conditions:

\rgi \rgi Independence:

\vspace{0.8in}

\rgi \rgi Success-Failure:

\vspace{0.8in}
    
\rgi Simulation P-value:
    
\vspace{0.3in}
       
\rgi \rgi Interpretation:
        
\vspace{0.8in}
        
\rgi \rgi Conclusion:
        
\vspace{0.8in}
        
\rgi \rgi Decision:
        
\vspace{0.3in}
    
\rgi Simulation Confidence Interval: 
    
\vspace{0.3in}
        
\rgi \rgi Interpretation:
        
\vspace{0.8in}

\rgi Standardized Statistic:

\vspace{0.3in}

\rgi \rgi Interpretation:

\vspace{0.8in}

\rgi Theory-based p-value:

\vspace{0.3in}

\rgi Theory-based Confidence Interval:

\vspace{0.5in}

\rgi Does the theory-based p-value and CI match those found using simulation methods?

\vspace{0.8in}

\rgi To what group can the results be generalized?

\vspace{0.8in}

        
3.  Write a research question involving two categorical variables that can be answered using the data set.  

\vspace{0.8in}

4. Use the provided Exam 2 Review `R` script file and analyze this research question.

\rgi Parameter of Interest:
    
\vspace{0.3in}
    
\rgi Null Hypothesis:
        
\rgi \rgi Notation:
    
\vspace{0.3in}
    
\rgi \rgi Words:
        
\vspace{0.5in}
    
\rgi Alternative Hypothesis:
    
\rgi \rgi Notation:
    
\vspace{0.3in}
    
\rgi \rgi Words:
        
\vspace{0.5in}
   
\rgi Statistic:
    
\vspace{0.3in}
    
\rgi Conditions:

\rgi \rgi Independence:

\vspace{0.8in}

\rgi \rgi Success-Failure:

\vspace{0.8in}
    
\rgi Simulation P-value:
    
\vspace{0.3in}
       
\rgi \rgi Interpretation:
        
\vspace{0.8in}
        
\rgi \rgi Conclusion:
        
\vspace{0.8in}
        
\rgi \rgi Decision:
        
\vspace{0.3in}
    
\rgi Simulation Confidence Interval: 
    
\vspace{0.3in}
        
\rgi \rgi Interpretation:
        
\vspace{0.8in}

\rgi Standardized Statistic:

\vspace{0.3in}

\rgi \rgi Interpretation:

\vspace{0.8in}

\rgi Theory-based p-value:

\vspace{0.3in}

\rgi Theory-based Confidence Interval:

\vspace{0.5in}

\rgi Does the theory-based p-value and CI match those found using simulation methods?

\vspace{0.8in}

\rgi What is the scope of inference for this study?

\vspace{0.8in}

\newpage