## Week 14 Lab: Efficacy of the COVID Vaccination

\setstretch{1}

### Learning outcomes

* Recognize and simulate probabilities as long-run frequencies.

* Use two-way tables to calculate conditional probabilities.

* Interpret the value of relative risk in terms of a percent increase or decrease.

* Evaluate the association between two categorical variables using relative risk.

### Efficacy of the COVID vaccination

In November 2021, it was estimated that 59.1\% of US adults ($\ge$ 18 years old) were fully vaccinated against COVID-19.   One factor of vaccination results in lower hospitalization rates. The following two-way table was created based on CDC data on vaccination results in the US.

|                   |  Vaccinated | Not Vaccinated |    Total   |
|-------------------|-------------|----------------|------------|
| Hospitalized      |     2.309   |      27.7302   |    30.0392 |
| Not hospitalized  | 59,097.6951 |   40,872.2698  |   99,96949 |
| Total             |   59,100    |      40,900    |    100,000 |


1.  What is the probability that a US adult is both hospitalized and vaccinated?

\vspace{0.5in}

2.  What is the probability that a US adult hospitalized with a COVID infection is vaccinated?

\vspace{0.5in}

3.  What is the probability that a US adult is hospitalized with a COVID infection in November 2021?

\vspace{0.5in}

4.  What is the probability that a vaccinated US adult is hospitalized?

\vspace{0.5in}

5.  What is the probability that a un-vaccinated US adult is hospitalized?

\vspace{0.5in}

6.  Calculate the relative risk for hospitalization in the November 2021 for US adults fully vaccinated compared US adults not vaccinated.

\vspace{0.5in}

7.  Calculate the percent increase (or decrease) in hospitalization rate for US adults fully vaccinated compared to US adults not vaccinated.

\vspace{0.5in}

8. Interpret the relative risk as a percent increase/decrease in context of the problem. 
\newpage