# Probability and Relative Risk

## Module 14 Reading Guide: Special Topics

### Chapter 23 (Probability with tables) {-}

\setstretch{1}

**Videos**

* Chapter23

\setstretch{1.25}

#### Vocabulary {-}

Random process:
\rgs

Probability:
\rgs

Hypothetical two-way table:
\rgs

Unconditional probability:
\rgs

\rgi Notation:
\rgs

Conditional probability:
\rgs

\rgi Notation:
\rgs

Event:
\rgs

\rgi Notation:
\rgs

Complement:
\rgs

\rgi Notation:
\rgs

Sensitivity:
\rgs

Specificity:
\rgs

Prevalence:
\rgs

#### Notes {-}

Method for creating a hypothetical two-way table:

1.	Start with
\rgs

2.	Fill in the column or row totals using
\rgs

3.	Fill in the interior cells using
\rgs

4.	Add/Subtract to fill in the row/column totals not filled in at step 2.

\rgi \rgi To find unconditional probabilities from the table,
\rgs

\rgi \rgi To find conditional probabilities from the table,
\rgs

#### Example from section 23.4: Baby Jeff {-}

1.	Let $D$ be the event a child has CPK.  What does $D^C$ represent?
\rgs

2.	Let $T$ be the event a child tests positive for CPK.  What does $T^C$ represent?
\rgs

3.	Write each of the following values in proper probability notation:
    a. $1/10000 = 0.0001 = P( \hspace{1in} )$
    b. $100\% = 1.0 = P(  \hspace{1in}  )$
    c. $99.98\% = 0.9998 = P(  \hspace{1in}  )$

4.	Write out the steps for creating the hypothetical two-way table in section 2.2.4 of your textbook, then copy the table below.

\rgi First,
\rgs

\rgi Next,
\rgs

\rgi After that,
\rgs

\rgi Finally,
\rgs

\rgi Hypothetical two-way table:

\begin{center}
\begin{tabular}{|l|p{1.3in}|p{1.3in}|p{1.3in}|}
\hline
&	Test Positive	& Test Negative	& Total \\ \hline
Has CPK		& & & \\
	& & & \\
	& & & \\ \hline
Does not have CPK		& & & \\
	& & & \\
	& & & \\ \hline
Total & & & 100,000 \\ \hline
\end{tabular}
\end{center}
\rgs

5.	What is the probability that a child who had a positive test result actually does have CPK?  What probability notation should be used for this value?
\rgs


6.	Explain how the probability in #5 was calculated.

\newpage

### Section 15.1.4 revisited (Simulation-based inference for a relative risk)  {-}

#### Vocabulary {-}

Relative risk: 
\rgs


#### Notes {-}

Interpreting relative risk ($RR = \frac{\hat{p_1}}{\hat{p_2}}$)

\rgi The proportion of success in group 1 is ______ times the proportion of success in group 2.

\rgi The proportion of success in group 1 is ______ % higher/lower than in group 2.

Write the null hypothesis in notation for a test of relative risk.
\rgs

#### Formulas {-}

Relative risk = 
\rgs

#### Example: Malaria Vaccine {-}

1. What is the research question?
\rgs

2. What are the observational units?
\rgs

3. What type of study design was used?  Justify your answer.
\rgs

4. What is the appropriate scope of inference for these data?
\rgs

5. What is the sample relative risk?  Interpret the value in the context of the study.
\rgs
\rgs

6. What is the parameter (using relative risk) representing in the context of this problem?  What notation would be used to represent this parameter?
\rgs
\rgs

7. Write the null and the alternative hypotheses in words.
\rgs
\rgs

8. Write the null and the alternative hypotheses in notation.
\rgs

9. How could we use cards to simulate **one** sample *which assumes the null hypothesis is true*?  How many blue cards --- to represent what?  How many red cards --- to represent what?  What would we do with the cards?  What would you record once you have a simulated sample?
\rgs
\rgs
\rgs

10. How can we calculate a p-value from the simulated null distribution for this example?
\rgs
\rgs

11. What was the p-value of the test? 
\rgs

12. Interpret the p-value in the context of the problem.
\rgs
\rgs

13. At the 5% significance level, what decision would you make?
\rgs

14. What conclusion should the researcher make?
\rgs
\rgs

15. Are the results in this example statistically significant?  Justify your answer.
\rgs



\newpage