# Data Exploration: Concussions

\setstretch{1}

### Learning objectives

1. Read research articles and 

2. 

### Concussions

Read through the following abstracts before class and be prepared to discuss the following questions in your groups.

(a) The questions researchers wanted to answer.

(b) Who/what were the subjects?

(c) Were treatments applied at random?


1. Petraglia AL, Plog BA, Dayawansa S, Chen M, Dashnaw ML, Czerniecka K, Walker CT, Viterise T, Hyrien O, Iliff JJ, Deane R, Nedergaard M, Huang JH. (2014). *The spectrum of neurobehavioral consequences after repetitive mild traumatic brain injury: a novel mouse model of chronic traumatic encephalopathy.*
J Neurotrauma Jul 1; 31(13):1211-24.

http://www.ncbi.nlm.nih.gov/pubmed/24766454

Abstract    

There has been an increased focus on the neurological consequences of repetitive mild traumatic brain injury (TBI), particularly neurodegenerative syndromes, such as chronic traumatic encephalopathy (CTE); however, no animal model exists that captures the behavioral spectrum of this phenomenon. We sought to develop an animal model of CTE. Our novel model is a modification and fusion of two of the most popular models of TBI and allows for controlled closed-head impacts to unanesthetized mice. Two-hundred and eighty 12-week-old mice were divided into control, single mild TBI (mTBI), and repetitive mTBI groups. Repetitive mTBI mice received six concussive impacts daily for 7 days. Behavior was assessed at various time points. Neurological Severity Score (NSS) was computed and vestibulomotor function tested with the wire grip test (WGT). Cognitive function was assessed with the Morris water maze (MWM), anxiety/risk-taking behavior with the elevated plus maze, and depression-like behavior with the forced swim/tail suspension tests. Sleep electroencephalogram/electromyography studies were performed at 1 month. NSS was elevated, compared to controls, in both TBI groups and improved over time. Repetitive mTBI mice demonstrated transient vestibulomotor deficits on WGT. Repetitive mTBI mice also demonstrated deficits in MWM testing. Both mTBI groups demonstrated increased anxiety at 2 weeks, but repetitive mTBI mice developed increased risk-taking behaviors at 1 month that persist at 6 months. Repetitive mTBI mice exhibit depression-like behavior at 1 month.  Both groups demonstrate sleep disturbances. We describe the neurological consequenses of repetitive mTBI in a novel mouse model, which resemble several of the neuropsychiatric behaviors observed clinically in patients sustaining repetitive mild head injury.
    
2. Lin, Ramadan, Stern, Box, Nowinski, Ross, Mountford. (2015). *Changes in the neurochemistry of athletes with repetitive brain trauma: preliminary results using localized correlated spectroscopy.* Alzheimers Research & Therapy.
2015 Mar 15;7(1):13

http://www.ncbi.nlm.nih.gov/pubmed/25780390

Abstract
INTRODUCTION:

The goal was to identify which neurochemicals differ in professional athletes with repetitive brain trauma (RBT) when compared to healthy controls using a relatively new technology, in vivo Localized COrrelated SpectroscopY (L-COSY).
    
METHODS:
    
To achieve this, L-COSY was used to examine five former professional male athletes with 11 to 28 years of exposure to contact sports. Each athlete who had had multiple symptomatic concussions and repetitive sub concussive trauma during their career was assessed by an experienced neuropsychologist. All athletes had clinical symptoms including headaches, memory loss, confusion, impaired judgment, impulse control problems, aggression, and depression. Five healthy men, age and weight matched to the athlete cohort and with no history of brain trauma, were recruited as controls. Data were collected from the posterior cingulate gyrus using a 3 T clinical magnetic resonance scanner equipped with a 32 channel head coil.
    
RESULTS:

The variation of the method was calculated by repeated examination of a healthy control and phantom and found to be 10% and 5%, respectively, or less. The L-COSY measured large and statistically significant differences (P <=0.05), between healthy controls and those athletes with RBT. Men with RBT showed higher levels of glutamine/glutamate (31%), choline (65%), fucosylated molecules (60%) and phenylalanine (46%). The results were evaluated and the sample size of five found to achieve a significance level P=0.05. Differences in N-acetyl aspartate and myoinositol between RBT and controls were small and were not statistically significance.

CONCLUSIONS:

A study of a small cohort of professional athletes, with a history of RBT and symptoms of chronic traumatic encephalopathy when compared with healthy controls using 2D L-COSY, showed elevations in brain glutamate/glutamine and choline as recorded previously for early traumatic brain injury. For the first time increases in phenylalanine and fucose are recorded in the brains of athletes with RBT. Larger studies utilizing the L-COSY method may over an in-life method of diagnosis and personalized approach for monitoring the acute effects of mild traumatic brain injury and the chronic effects of RBT.
    
3. Here's a quote from a news report in 2013:
"We need to figure out what's making some people more vulnerable than others," says Michelle Mielke, an Alzheimer's researcher at the Mayo Clinic who led the study. It was published online Thursday in the journal Neurology. Just because you have a head trauma doesn't mean you're going to develop memory problems or significant amyloid levels," Mielke told Shots. And it doesn't
mean you're going to get Alzheimer's. "But it does suggest to us that there's a mechanism with head trauma that does increase your risk."

Mielke and her colleagues did PET scans on 589 people who are participating in a long-term study of aging and memory. That's a lot of people for a brain imaging study, which makes it more likely that the findings are accurate.

http://www.npr.org/blogs/health/2013/12/27/257552665/concussions-may-increase-alzheimers-risk-but-only-for-some

### Concussions in the News

*  Chris Borland, age 24, retired from the 49ers after one year of NFL play, because he fears his brain might be permanently injured by concussions. 

*  In 2013 the NFL agreed to pay $765 million to fund exams, research and for compensation of former players.

*  High school coaches are now advised to make their players sit out if they sustain
a blow to the head.

*  The Congressional Brain Injury Task Force is looking into the prevalence of brain trauma in troops deployed in recent wars and at how VA hospitals are treating the condition.

### Applying What We've Learned

Some have argued that blows to the head - for instance on the high school football field - are getting too much attention. They point out that of many kids taking similar hits, only a few show lasting decrease in cognitive abilities, and suggest that the effects are as much due to genetics as to the blow to the head.

1. Your group is asked to design a study to determine how large a risk the "hits"
taken by high school athletes are to their future cognitive abilities. Write down
a plan for your study. Include:

*  Who will your subjects be? How will you find them? How many will you need?

*  What will you measure? (Brain scans like MRI? Cognitive tests of memory and reasoning? Some measure of emotional states like anger?) Include the timing of measurements.

*  Will your study be observational or an experiment?

*  Is your study ethical in its treatment of subjects?

\vspace{1in}

2. Trade papers with another group and read their study over carefully. Address the bullet points above. Provide suggestions as to what might be improved.

*  Subjects?

\vspace{0.5in}

*  Measurements?

\vspace{0.5in}

*  Observational? Experiment?

\vspace{0.5in}

*  Ethical issues?

\vspace{0.5in}


3. For today's class you read the abstract from this article.

Petraglia AL, Plog BA, Dayawansa S, Chen M, Dashnaw ML, Czerniecka K, Walker CT, Viterise T, Hyrien O, Iliff JJ, Deane R, Nedergaard M, Huang JH. (2014). *The spectrum of neurobehavioral consequences after repetitive mild traumatic brain injury: a novel mouse model of chronic traumatic encephalopathy.* J Neurotrauma Jul 1; 31(13):1211-24.

http://www.ncbi.nlm.nih.gov/pubmed/24766454

(a) What are the advantages of this study design?

\vspace{0.5in}

(b) Disadvantages?

\vspace{0.5in}

(c) Does the design allow us to make causal inferences? Explain.

\vspace{0.5in}

(d) Inferences to high school students? Explain.

\vspace{0.5in}

4. And you read this abstract:
Lin, Ramadan, Stern, Box, Nowinski, Ross, Mountford. (2015). *Changes in the neurochemistry of athletes with repetitive brain trauma: preliminary results using localized correlated spectroscopy.* Alzheimers Research & Therapy.
2015 Mar 15;7(1):13

http://www.ncbi.nlm.nih.gov/pubmed/25780390

(a) What are the advantages of this study design?

\vspace{0.5in}

(b) Disadvantages?

\vspace{0.5in}

(c) Does the design allow us to make causal inferences? Explain.

\vspace{0.5in}

(d) Inferences to high school students? Explain.

\vspace{0.5in}

5. Here's a quote from a news report in 2013:
"Mielke and her colleagues did PET scans on 589 people who are participating in a long-term study of aging and memory. That's a lot of people for a brain imaging study, which makes it more likely that the findings are accurate."

http://www.npr.org/blogs/health/2013/12/27/257552665/concussions-may-increase-alzheimers-risk-but-only-for-some

Explain the last sentence. In what sense does a large sample increase accuracy?

\vspace{1in}

### Take Home Messages

1. In reading a research article, carefully read what they say about selection of subjects (or units of study) so we know how far we can extend our inference.

2. Similarly, evaluate the assignment of any treatments (at random, we hope) so that we know if causal inference is appropriate.

3.  In designing a study, we'd like to get a large sample, but expense might prevent that.

4. You might see names of tests we've not covered, but the idea of a p-value is the same for any test, and the null hypothesis is generally "No change", or "No effect".

### Additional notes

Use this space to summarize your thoughts and take additional notes on today's activity and material covered.

\newpage